library(arules)
library(arulesViz)
library(datasets)
data(Groceries)
str(Groceries)
inspect(Groceries[1:5])
inspect(Groceries[9830:9835])
itemFrequencyPlot(Groceries,topN=10,type="absolute")
rules <- apriori(Groceries, parameter = list(supp = 0.001, conf = 0.8))
options(digits=2)
inspect(rules[1:5])
rules<-sort(rules, by="confidence", decreasing=TRUE)
inspect(rules[1:5])
rules<-apriori(data=Groceries, parameter=list(supp=0.001,conf = 0.15,minlen=2),appearance = list(default="rhs",lhs="whole milk"),control = list(verbose=F))
rules<-sort(rules, decreasing=TRUE,by="confidence")
inspect(rules[1:5])
rules <- apriori(Groceries, parameter = list(supp = 0.001, conf = 0.8,maxlen=3))
rules <- apriori(Groceries, parameter = list(supp = 0.001, conf = 0.8))
redundant <- is.redundant(rules)
redundant
rules.pruned <- rules[!redundant]
rules<-rules.pruned
rules
inspect(rules[1:5])
summary(rules)
library(arulesViz)
rules<-apriori(data=Groceries, parameter=list(supp=0.001,conf = 0.15,minlen=2), appearance = list(default="rhs",lhs="whole milk"),control = list(verbose=F))
rules<-sort(rules, decreasing=TRUE,by="confidence")
inspect(rules[1:5])
plot(rules,method="graph",interactive=TRUE ,shading=NA)
